[package]
name = "gl-front"
version = "0.1.0"
authors = ["Ã˜yvind <oyvind.nordsveen@gmail.com>"]

[dependencies]
glutin = "0.17.0"
gl = { path = "../gl" }
failure = "0.1"

[build-dependencies]
walkdir = "2.1"